# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
all:
  vars:
    users:
      # If you need to remove access from someone, do not remove them from this list, but instead set their state: absent
      - name: provision
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQClZ2OM4aj2c+jx7631wFGSV0tG/rOT6OL5Xh7Azb6cjwAZSJgRCTVh3hiDN03x2M1aM8CtW25Xi6mh4eF+R+uWdSEpZBWYAF7S4/4sVwGNqC0776Z3EcE7zqGmxzfESxBkO07d7tW3qEee6ZK0LxJm8x1X9NIA0Km5LEbLIz5/BNk42etqKi7AyqqDAnF22jQ+6mRgX1w06aXOWrd/N7krzzwSTUJ4urPHrfr+fkMbv1rDc7Q+WTRXMhykBaMxgIlBbeYv+Hi4TWJ+k0Wl0r1tUe7eRh9ehOxby6EWCbpG4Sh1UfGjyQRwo2hQH09yQ6KQhotn9ov9Bv8X0P++5jKbDJbevmTTnJTFastY9KDzZdFGUVfqNTkLk/KWvFMnVX7ABWp3n0kCc/0B8sQ4Zrd6oN9TCG+RVr+njom6LFUqnvp/z6hdAGT/qMR2OkBX5kJSqnNdwfHsLGT/e8z7FC+9k6qVoZpOEyIMzhBBUWyh3zSMfPPUC0FnBMpxgD9ZTjc= provision@ip-172-31-46-96
        state: present
        sudoer: true

docker-manager-first:
  hosts:
    ip-172-31-46-96:
      ansible_host: '35.80.140.106'
      data_label: data1

# QA and staging servers are not configured to use workers.
docker-workers: {}
